services:

    copier:
        image: busybox
        volumes:
            - nfs:/shared
            - ./shared:/nfs-copy
        command: [ "/bin/sh", "-c", "cp -ru /nfs-copy/* /shared/ && echo 'Updated content:' && ls -l /shared" ]

volumes:
    nfs:
        driver_opts:
            type: "nfs"
            o: "addr=${SERVER_IP},rw"
            device: ":/srv/nfs/shared"
