version: "3.7"

services:
    
    nginx:
        image: nginx:latest
        environment:
            - BACKEND_SERVER_NAME=${BACKEND_SERVER_NAME}
            - FRONTEND_SERVER_NAME=${FRONTEND_SERVER_NAME}
        ports:
            - "80:80"
            - "443:443"
            - "8080:8080"
        volumes:
            # - wordpress-html:/var/www/html
            - nginx-config:/etc/nginx/nginx.conf:ro
            - nginx-templates:/etc/nginx/templates
            # - /etc/letsencrypt/live/<domain>/fullchain.pem:/etc/nginx/ssl/fullchain.pem:ro
            # - /etc/letsencrypt/live/<domain>/privkey.pem:/etc/nginx/ssl/privkey.pem:ro
        networks:
            - intranet
        deploy:
            replicas: 1
            placement:
                constraints: [node.role == manager]
            restart_policy:
                condition: on-failure

volumes:

    nginx-config:
        driver_opts:
            type: "nfs"
            o: "addr=${SERVER_IP},rw"
            device: ":/srv/nfs/shared/configs/nginx/nginx.conf"

    nginx-templates:
        driver_opts:
            type: "nfs"
            o: "addr=${SERVER_IP},rw"
            device: ":/srv/nfs/shared/configs/nginx/templates"

    # wordpress-html:
    #     driver_opts:
    #         type: "nfs"
    #         o: "addr=${SERVER_IP},rw"
    #         device: ":/srv/nfs/shared/wordpress/html"

networks:
    intranet:
        external: true
