version: "3.7"

services:
    initializer:
        image: busybox
        volumes:
            - nfs:/shared
            - ./configs:/configs
            - ./wordpress/plugins:/wordpress/plugins
        command: ["/bin/sh", "-c", "cp -r /configs/* /shared/", "cp -r /wordpress/* /shared/wordpress/"]
        deploy:
            replicas: 1
            placement:
                constraints: [node.role == manager]
            restart_policy:
                condition: none


    nginx:
        image: nginx:latest
        environment:
            - BACKEND_SERVER_NAME=${BACKEND_SERVER_NAME}
            - FRONTEND_SERVER_NAME=${FRONTEND_SERVER_NAME}
        ports:
            - "80:80"
            - "443:443"
            - "8080:8080"
        volumes:
            - nfs/wordpress/html:/var/www/html
            - nfs/configs/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
            - nfs/configs/nginx:/etc/nginx/templates
            # - /etc/letsencrypt/live/<domain>/fullchain.pem:/etc/nginx/ssl/fullchain.pem:ro
            # - /etc/letsencrypt/live/<domain>/privkey.pem:/etc/nginx/ssl/privkey.pem:ro
        networks:
            - intranet
        deploy:
            replicas: 1
            placement:
                constraints: [node.role == manager]
            restart_policy:
                condition: on-failure

volumes:
    nfs:
        driver_opts:
            type: "nfs"
            o: "addr=${SERVER_IP},rw"
            device: ":/srv/nfs/shared"

networks:
    intranet:
        external: true
