version: "3.7"

services:
    nfs-server:
        image: erichough/nfs-server
        cap_add:
            - SYS_ADMIN
        networks:
            - intranet
        volumes:
            - ./shared:/nfs-data:rw
        environment:
            NFS_EXPORT_0: nfs-data *(rw,no_subtree_check)

networks:
    intranet:
        external: true
# docker stack deploy -c nfs.yml nfs --detach=true
