version: "3.7"

services:
    initializer:
        image: busybox
        volumes:
            - nfs:/shared
            - ./shared:/nfs-copy
        command: ["/bin/sh", "-c", "cp -r /nfs-copy/* /shared/"]
        deploy:
            replicas: 1
            placement:
                constraints: [node.role == manager]
            restart_policy:
                condition: none

    nginx:
        image: nginx:latest
        environment:
            - BACKEND_SERVER_NAME=${BACKEND_SERVER_NAME}
            - FRONTEND_SERVER_NAME=${FRONTEND_SERVER_NAME}
        ports:
            - "80:80"
            - "443:443"
            - "8080:8080"
        volumes:
            - type: volume
              source: nfs
              volume:
                  subpath: /wordpress/html
              target: /var/www/html
            - type: volume
              source: nfs
              volume:
                  subpath: /configs/nginx/nginx.conf
              target: /etc/nginx/nginx.conf
              read_only: true
            - type: volume
              source: nfs
              volume:
                  subpath: /configs/nginx
              target: /etc/nginx/templates
              read_only: true
            # - /etc/letsencrypt/live/<domain>/fullchain.pem:/etc/nginx/ssl/fullchain.pem:ro
            # - /etc/letsencrypt/live/<domain>/privkey.pem:/etc/nginx/ssl/privkey.pem:ro
        networks:
            - intranet
        deploy:
            replicas: 1
            placement:
                constraints: [node.role == manager]
            restart_policy:
                condition: on-failure

volumes:
    nfs:
        driver_opts:
            type: "nfs"
            o: "addr=${SERVER_IP},rw"
            device: ":/srv/nfs/shared"

networks:
    intranet:
        external: true
