version: "3.7"

services:
    nginx:
        image: nginx:latest
        environment:
            - BACKEND_SERVER_NAME=${BACKEND_SERVER_NAME}
            - FRONTEND_SERVER_NAME=${FRONTEND_SERVER_NAME}
        ports:
            - "80:80"
            - "443:443"
            - "8080:8080"
        volumes:
            # - wordpress-html:/var/www/html
            - nginx-configs:/mnt/nginx
            # - /etc/letsencrypt/live/<domain>/fullchain.pem:/etc/nginx/ssl/fullchain.pem:ro
            # - /etc/letsencrypt/live/<domain>/privkey.pem:/etc/nginx/ssl/privkey.pem:ro
        entrypoint:
            [
                "/bin/sh",
                "-c",
                "ln -sf /mnt/nginx/nginx.conf /etc/nginx/nginx.conf && ln -sf /mnt/nginx/templates /etc/nginx/templates && exec nginx -g 'daemon off;'",
            ]
        networks:
            - intranet
        deploy:
            replicas: 1
            placement:
                constraints: [node.role == manager]
            restart_policy:
                condition: on-failure

volumes:
    nginx-configs:
        driver_opts:
            type: "nfs"
            o: "addr=${SERVER_IP},rw"
            device: ":/srv/nfs/shared/configs/nginx"

    # wordpress-html:
    #     driver_opts:
    #         type: "nfs"
    #         o: "addr=${SERVER_IP},rw"
    #         device: ":/srv/nfs/shared/wordpress/html"

networks:
    intranet:
        external: true
