global:
    scrape_interval: 15s

scrape_configs:
    # Make Prometheus scrape itself for metrics.
    - job_name: "prometheus"
      static_configs:
          - targets: ["prometheus:9090"]

    - job_name: "nginx"
      static_configs:
          - targets: ["nginx-exporter:9113"]

    - job_name: "wordpress"
      dns_sd_configs:
          - names:
                - "tasks.wordpress-exporter"
            type: "A"
            port: 9253
      metrics_path: "/metrics"

    - job_name: mysql # To get metrics about the mysql exporter’s targets
      static_configs:
          - targets: ["mysql-exporter:9104"]

    # Create a job for Docker Swarm nodes.
    - job_name: "docker_nodes"
      dockerswarm_sd_configs:
          - host: unix:///var/run/docker.sock
            role: nodes
      relabel_configs:
          # Fetch metrics on port 9323.
          - source_labels: [__meta_dockerswarm_node_address]
            target_label: __address__
            replacement: $1:9323
          # Set hostname as instance label
          - source_labels: [__meta_dockerswarm_node_hostname]
            target_label: instance

    # Create a job for Docker Swarm tasks.
    - job_name: "dockerswarm_tasks"
      dockerswarm_sd_configs:
          - host: unix:///var/run/docker.sock
            role: tasks
      relabel_configs:
          # Only keep containers that should be running.
          - source_labels: [__meta_dockerswarm_task_desired_state]
            regex: running
            action: keep
          # Only keep containers that have a `prometheus-job` label.
          - source_labels: [__meta_dockerswarm_service_label_prometheus_job]
            regex: .+
            action: keep
          # Use the prometheus-job Swarm label as Prometheus job label.
          - source_labels: [__meta_dockerswarm_service_label_prometheus_job]
            target_label: job
          # Only scrape tasks that are on the 'intranet' network.
          - source_labels: [__meta_dockerswarm_network_name]
            regex: intranet
            action: keep
          # Add docker_node label.
          - source_labels: [__meta_dockerswarm_node_hostname]
            target_label: docker_node
